### ISSUE TITLE
Looking for 7.3.0

### ISSUE THREAD

**Issue by karthikgreentrend** [walterra/kibana-milestones-vis#11]
Could you please guide me on how to release 7.3.0 I will do myself and release it here

**Comment by walterra** [comment]
Hi! Thanks for the support! Kibana 7.2.0 [had quite some changes in how its APIs](https://www.elastic.co/blog/kibana-plugin-api-changes-in-7-2) work and I'm half-through doing the new releases. You're always welcome to fork and create a PR but in this case it would a bit of a waste of efforts since I'm working on it already. Unfortunately I can't give you a fixed date when this will be done, hopefully soonish.

**Comment by karthikgreentrend** [comment]
thanks a lot @walterra

**Comment by walterra** [comment]
This took way longer than expected, but the wait is over, here's the 7.3.0 release: https://github.com/walterra/kibana-milestones-vis/releases/tag/v7.3.0
