### ISSUE TITLE
6.8.2 Breaks Kibana

### ISSUE THREAD

**Issue by YaariBoaz** [walterra/kibana-milestones-vis#16]
Hey,

I am running ELK on window 10.
Everything is working fine if I don't install this plugin.

I am using Kibana 6.8.2 -  and downloaded the kibana-milestones-vis-6.8.2.zip.
The installation goes smooth and I get the  "Plugin installation complete" message.
When I run Kibana.bat it all goes well.

But, When I try loading it I get  two  errors:

1. Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'unsafe-eval' self". Either the 'unsafe-inline' keyword, a hash (....), or a nonce (nonce-...) is required to enable inline execution.

2. Error: [$compile:tplrt] Template for directive 'kbnNotifications' must have exctly one root element.

Any help?

**Comment by walterra** [comment]
Just tried to reproduce this on a fresh Windows 7 and it worked. Here's what I did:

- Install Java 14 from https://www.oracle.com/java/technologies/javase-jdk14-downloads.html
- Install Git Bash from https://git-scm.com/download/win
- Download ES 6.8.2 via https://www.elastic.co/downloads/past-releases/elasticsearch-6-8-2
  - In Git Bash CLI: I used `unzip elasticsearch-6.8.2.zip` in git bash since unzipping in Explorer takes ages. 
  - In regular `cmd.exe` cli: Within the unzipped directory, run `bin\elasticsearch.bat`
- Download Kibana 6.8.2 via https://www.elastic.co/downloads/past-releases/kibana-6-8-2
  - In Git Bash CLI: Again, I use `unzip kibana-6.8.2.zip` because it's unusably slow in Explorer.
  - In regular `cmd.exe` cli: `bin/kibana-plugin.bat install https://github.com/walterra/kibana-milestones-vis/releases/download/v6.8.2/kibana-milestones-vis-6.8.2.zip` — note the optimize step took a few minutes for me, here's the output of the installation: ![image](https://user-images.githubusercontent.com/230104/86005815-66343b00-ba15-11ea-96ba-fe094f91bd17.png)
  - Then start Kibana: `bin\kibana.bat`, I set up the `flights` sample dataset and ran the plugin: 
![image](https://user-images.githubusercontent.com/230104/86006943-06d72a80-ba17-11ea-8464-f515f9f88397.png)

The error you are seeing, does that happen right on the Kibana home page or only when you try to create a milestones visualization? If it happens when you access the plugin, can you please post the exact steps you are taking until you get the error? Maybe also try with one of the sample datasets from Kibana (flights,logs or ecommerce).

Could you try to install another visualization plugin from this list and see if it's successful or you get similar errors? https://www.elastic.co/guide/en/kibana/current/known-plugins.html

**Comment by YaariBoaz** [comment]
Hey @walterra ,
Thanks for the detailed answer.
I have taken a few weeks to investigate it from my side in order  to be sure and it came to two things that might be wrong:
1. I am working offline - No internet.
2.I am using Windows 10.

Do any of the two block me from using this plugin ?

Thanks.

**Comment by walterra** [comment]
If have you have everything on your machine it should work offline. I will try to reproduce with Windows 10.

**Comment by walterra** [comment]
Was unable to reproduce. Feel free to reopen if you encounter this and can provider more details.
